### ISSUE TITLE
README states that Auto-Vk requires only a C++17 compiler, but it uses C++20 features

### ISSUE THREAD

**Issue by lHerzberger** [cg-tuwien/Auto-Vk#18]
[std::basic_string<CharT,Traits,Allocator>::ends_with](https://en.cppreference.com/w/cpp/string/basic_string/ends_with) (used in `avk.cpp`) is a C++20 feature.

**Comment by johannesugb** [comment]
Thanks for pointing that out. I'm using the `std::c++latest` feature set in MSVC which obviously already includes some C++20 features.

Does this cause any problems with GCC or Clang? 
What did you have to adjust with those compilers to make it compile?

**Comment by lHerzberger** [comment]
I only had to set the C++ Standard from 17 to 20 in `CMakeLists.txt`, so it wasn't that big of a deal.
I forgot to update the `README` though.

**Comment by lHerzberger** [comment]
The readme has been updated in the meantime. Closing this.
