### ISSUE TITLE
Add .gitignore

### ISSUE THREAD

**Issue by electrocnic** [cg-tuwien/Auto-Vk#32]
Hi,

Would you mind adding a .gitignore?
I get `modified:   gears_vk (untracked content)` by `git status` when I build gears_vk because auto_vk will produce an out/ directory.
As auto_vk is a submodule, I do not wish to change anything inside, and an external .gitignore has no effect on folders/files inside submodules.

Thanks so much!

**Comment by johannesugb** [comment]
Hmm, that's strange. Afaik, we don't see that behavior when building with Visual Studio 2019.
Would you mind sharing some details about how exactly you are building so that you get an `gears_vk/auto_vk/out/` directory?

**Comment by electrocnic** [comment]
Oh I am so sorry, my fault, I'm sorry for the inconvenience.
As I deleted those "out" folders and rebuilt the solution, it did not create those folders anymore.

I cannot even reproduce the generation of the out folder anymore. Should have checked upfront.
