### ISSUE TITLE
Some examples to get auto vk running for people wanting to use this instead of auto-vk toolkit

### ISSUE THREAD

**Issue by Sirtsu55** [cg-tuwien/Auto-Vk#71]
So I have encountered difficulties when using this library. To be specific, I find it difficult integrating this into my project. I think the lack of examples and documentation probably pushes people away from auto vk, even though it looks like a really nice library.

**Comment by electrocnic** [comment]
Please have a look into https://github.com/cg-tuwien/Auto-Vk-Toolkit which uses Auto-Vk as a submodule and also provides a lot of examples. Hope this helps.
